#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and:
# display bad luck for the 4th loop iteration
# display good luck for the 8th loop iteration
# display Best School for the other iterations

printMessage=1
while [ $printMessage -lt 11 ]
do
	if [ "$printMessage" == "4" ]
	then
		echo "bad luck"
	elif [ "$printMessage" == "8" ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	printMessage=$((printMessage+1))
done
